// Generato da app/src/main/res/values/strings.xml (testi identici) + testi nuovi del web.
const regolePlurali = new Intl.PluralRules("it");

function scegliPlurale(n: number, forme: Record<string, string> & { other: string }): string {
  return forme[regolePlurali.select(n)] ?? forme.other;
}

export const t = {
  appName: "Imposteur",
  interromperePartita: "Interrompere la partita?",
  interrompereMessaggio: "La partita andrà persa.",
  interrompereConferma: "Interrompi",
  interrompereContinua: "Continua a giocare",
  indietro: "Indietro",
  tornaHome: "Torna alla Home",
  distribuzioneTitolo: "Distribuzione dei ruoli",
  annulla: "Annulla",
  homeTitolo: "Imposteur",
  nuovaPartita: "Nuova partita",
  riprendiPartita: "Riprendi partita",
  partitaInCorsoConferma: "Esiste una partita in corso. Iniziarne una nuova?",
  comeSiGioca: "Come si gioca",
  erroreCaricamentoParole: "Impossibile caricare le parole",
  regoleModalitaSenzaParolaTitolo: "Impostore senza parola",
  regoleModalitaSenzaParola: "Ogni giocatore, a turno, scopre in segreto il proprio ruolo. I civili vedono la parola segreta; l'impostore non la vede e, se l'opzione è attiva, vede soltanto la categoria. Poi si discute a voce: ognuno dà indizi sulla parola senza dirla, l'impostore cerca di non farsi scoprire.",
  regoleModalitaAffineTitolo: "Parola affine",
  regoleModalitaAffine: "Tutti i giocatori vedono una parola. I civili hanno la parola segreta, gli impostori una parola affine, simile ma diversa. Nessuno sa se ha la parola vera o quella affine: discutendo a voce bisogna capire chi ha una parola diversa.",
  regoleFineTitolo: "Come finisce",
  regoleFine: "Dopo la discussione si vota. Quando avete deciso, premete Rivela per scoprire chi era l'impostore e quale era la parola. I civili sono sempre più numerosi degli impostori.",
  configTitolo: "Configurazione",
  configGiocatoreN: (p1: number): string => `Giocatore ${p1}`,
  configNumeroImpostori: "Numero impostori",
  configModalita: "Modalità",
  modalitaSenzaParola: "Impostore senza parola",
  modalitaAffine: "Parola affine",
  configNumeroImpostoriMax: "Impostori (massimo)",
  configMostraCategoria: "L'impostore vede la categoria",
  configCategorie: "Categorie",
  configSelezionaTutte: "Seleziona tutte",
  configDeselezionaTutte: "Deseleziona tutte",
  configNomeDuplicato: "Nome già usato",
  configNessunaCategoria: "Seleziona almeno una categoria",
  configPoolVuoto: "Le categorie scelte non contengono parole utilizzabili",
  configInizia: "Inizia",
  configNonValida: "Controlla la configurazione",
  configParoleRimanenti: (p1: number, p2: number): string => `Parole ancora da giocare: ${p1} / ${p2}`,
  configAzzera: "Azzera",
  configAzzeraConferma: "Rimettere in gioco tutte le parole delle categorie scelte?",
  configDiminuisci: "Diminuisci",
  configAumenta: "Aumenta",
  opzTitolo: "Opzioni avanzate",
  opzAttive: (n: number): string => scegliPlurale(n, {
    one: `${n} attiva`,
    other: `${n} attive`,
  }),
  opzGruppoRuoli: "Ruoli",
  opzGruppoTurni: "Turni",
  opzGruppoFine: "Fine partita",
  opzDescVedeCategoria: "Aiuta l'impostore a bluffare.",
  opzNonPrimo: "L'impostore non parla per primo",
  opzDescNonPrimo: "Chi inizia è sempre un civile.",
  opzSorpresa: "Impostori a sorpresa",
  opzDescSorpresa: "Il numero di impostori è casuale, da 1 al massimo scelto.",
  opzTrappola: "Partita trappola",
  opzDescTrappola: "1 partita su 10 non ha nessun impostore.",
  opzOrdineCasuale: "Ordine di parola casuale",
  opzDescOrdineCasuale: "L'ordine viene mescolato, non segue la lista.",
  opzGiri: "Giri di indizi",
  opzDescGiri: "Quante volte ripetere l'ordine di parola.",
  opzPromemoria: "Promemoria: ultima possibilità",
  opzDescPromemoria: "Alla fine ricorda che l'impostore può ancora vincere indovinando la parola.",
  opzBreveNonPrimo: "Non parla per primo",
  opzBreveTrappola: "Trappola",
  opzBreveOrdineCasuale: "Ordine casuale",
  opzBreveGiri: (n: number): string => `${n} giri`,
  opzBrevePromemoria: "Promemoria",
  distribuzioneIndicatore: (p1: number, p2: number): string => `Giocatore ${p1} di ${p2}`,
  distribuzionePassa: (p1: string): string => `Passa il telefono a ${p1}`,
  distribuzionePassaA: "Passa il telefono a",
  distribuzioneTieniPremuto: "Tieni premuto per scoprire",
  distribuzioneSonoPremuto: (p1: string): string => `Sono ${p1} — tieni premuto`,
  distribuzioneTocca: "Tocca per scoprire",
  distribuzioneSonoTocca: (p1: string): string => `Sono ${p1} — tocca`,
  distribuzioneScopriCd: "Scopri il ruolo",
  distribuzioneTuttiPronti: "Tutti pronti!",
  distribuzioneBluff: "Che il bluff abbia inizio",
  distribuzioneNascondi: "Nascondi e passa",
  distribuzioneNascondiUltimo: "Nascondi e inizia",
  distribuzioneNonGuardare: "Gli altri non guardino lo schermo",
  ruoloLaParolaE: "La parola è:",
  ruoloLaTuaParolaE: "La tua parola è:",
  ruoloSeiImpostore: "Sei l'impostore",
  ruoloCategoria: (p1: string): string => `Categoria: ${p1}`,
  giocoTitolo: "Si gioca!",
  giocoInizia: "Parla per primo:",
  giocoIstruzioni: "Discutete a voce, poi votate. Quando avete deciso, premete Rivela.",
  giocoOrdineTitolo: "Ordine di parola",
  giocoRivela: "Rivela",
  giocoConfermaRivela: "Rivelare i ruoli?",
  giocoConfermaMessaggio: "Verrà mostrato chi era l'impostore.",
  giocoConfermaSi: "Rivela",
  giocoConfermaNo: "Non ancora",
  giocoGiroN: (p1: number): string => `Giro ${p1}`,
  giocoRivedi: "Rivedi la parola",
  rivediTitolo: "Rivedi la parola",
  rivediIntestazione: "Chi vuole rivedere la parola?",
  rivediSottotitolo: "Tocca il tuo nome",
  rivediCdGiocatore: (p1: string): string => `Rivedi la parola di ${p1}`,
  rivediTornaGioco: "Torna al gioco",
  rivediNascondi: "Nascondi",
  rivelaTitolo: "Il risultato",
  rivelaImpostore: "L'impostore era:",
  rivelaImpostori: "Gli impostori erano:",
  rivelaTrappola: "Nessun impostore: era una partita trappola!",
  rivelaPromemoria: "L'impostore scoperto può provare a indovinare la parola: se ci riesce, vince lui!",
  rivelaParola: (p1: string): string => `La parola era: ${p1}`,
  rivelaAffine: (p1: string): string => `La parola affine era: ${p1}`,
  rivelaCategoria: (p1: string): string => `Categoria: ${p1}`,
  rivelaCambiaImpostazioni: "Modifica giocatori e opzioni",
  rivelaRigioca: "Rigioca (stessi giocatori)",
  segnalaPulsante: "Segnala la coppia",
  segnalaTitolo: "Segnala la coppia",
  segnalaSottotitoloCoppia: (p1: string, p2: string): string => `${p1} / ${p2}`,
  segnalaCategoria: (p1: string): string => `Categoria: ${p1}`,
  segnalaMotivoSimili: "Parole troppo simili",
  segnalaMotivoDiverse: "Parole troppo diverse",
  segnalaMotivoPocoConosciuta: "Parola poco conosciuta",
  segnalaMotivoCategoria: "Categoria sbagliata",
  segnalaCommento: "Commento (facoltativo)",
  segnalaProponi: "Proponi una coppia (facoltativo)",
  segnalaProponiParola: "Parola",
  segnalaProponiAffine: "Parola affine",
  segnalaProponiManca: "Compila entrambe le parole",
  segnalaProponiUguali: "Le due parole devono essere diverse",
  segnalaContatore: (p1: number, p2: number): string => `${p1} / ${p2}`,
  segnalaSalva: "Salva",
  segnalaSalvata: "Segnalazione salvata, grazie!",
  impostazioniTitolo: "Impostazioni",
  impostazioniApri: "Apri le impostazioni",
  impostazioniPressioneTitolo: "Pressione per scoprire",
  impostazioniPressioneEtichetta: "Durata della pressione",
  impostazioniPressioneDescrizione: "Quanto tempo tenere premuto per scoprire il ruolo. Con 0 basta un tocco.",
  impostazioniPressioneValore: (p1: number): string => `${p1} ms`,
  impostazioniPressioneA11y: (p1: number): string => `${p1} millisecondi`,
  impostazioniPressioneA11yZero: "0 millisecondi, basta un tocco",
  temaTitolo: "Tema",
  temaSistema: "Sistema",
  temaChiaro: "Chiaro",
  temaScuro: "Scuro",
  temaAltoContrasto: "Alto contrasto",
  coloriTelefono: "Colori del telefono",
  coloriTelefonoDescrizione: "Usa i colori dello sfondo (Android 12+)",
  segnalazioniTitolo: "Segnalazioni",
  segnalazioniSuggerimenti: "Suggerimenti sull'app",
  segnalazioniInvia: "Invia",
  segnalazioniSalvate: (p1: number): string => `Segnalazioni salvate: ${p1}`,
  segnalazioniCancella: "Cancella tutte",
  segnalazioniCancellaConferma: "Cancellare tutte le segnalazioni salvate?",
  segnalazioniCancellaSi: "Cancella",
  segnalazioniLocale: "Restano solo su questo telefono.",

  // Configurazione in 5 passi (specifiche 4.2, design 5)
  modalitaSenzaParolaDesc: "I civili conoscono la parola, l'impostore deve bluffare.",
  modalitaAffineDesc: "L'impostore riceve una parola simile ma diversa.",
  passoAvanti: "Avanti",
  passoModifica: "Modifica",
  passoGiocatori: "Giocatori",
  passoModalita: "Modalità",
  passoOpzioni: "Opzioni",
  passoRiepilogo: "Riepilogo",
  passoEtichetta: (p1: number, p2: number, p3: string): string => `Passo ${p1} di ${p2} · ${p3}`,
  passoEtichettaCd: (p1: number, p2: number, p3: string): string => `Passo ${p1} di ${p2}: ${p3}`,
  passo1Titolo: "Chi gioca?",
  passo1Sottotitolo: "Come vi chiamate. Da 3 a 20 giocatori.",
  passo2Titolo: "Come si gioca?",
  passo2Sottotitolo: "Scegli la modalità e quanti impostori.",
  passo3Titolo: "Opzioni avanzate",
  passo3Sottotitolo: "Sono tutte facoltative: puoi andare avanti senza toccarle.",
  passo4Titolo: "Categorie",
  passo4Sottotitolo: "Da quali argomenti pescare le parole.",
  passo5Titolo: "Tutto pronto?",
  passo5Sottotitolo: "Controlla e inizia.",
  giocatoriAggiungi: "+ Aggiungi giocatore",
  giocatoriMassimo: "Massimo 20 giocatori",
  giocatoriRimuovi: (p1: number): string => `Rimuovi giocatore ${p1}`,
  riepGiocatori: (n: number): string => scegliPlurale(n, {
    one: `${n} giocatore`,
    other: `${n} giocatori`,
  }),
  riepImpostori: (n: number): string => scegliPlurale(n, {
    one: "1 impostore",
    other: `${n} impostori`,
  }),
  riepFinoA: (p1: number): string => `fino a ${p1} impostori`,
  riepCategorie: (n: number): string => scegliPlurale(n, {
    one: "1 categoria",
    other: `${n} categorie`,
  }),
  riepNessunaOpzione: "Nessuna opzione attiva",
  riepSenzaCategoria: "senza categoria",

  // Testi nuovi del web
  esportaSegnalazioni: "Esporta segnalazioni",
  condividiSegnalazioni: "Condividi",
  segnalazioniSalvateN: (n: number): string => (n === 1 ? "1 segnalazione salvata" : `${n} segnalazioni salvate`),
  installaIos: "Per installare l'app su iPhone: tocca Condividi, poi Aggiungi a Home.",
} as const;
